### PR TITLE
Reimplement path condition analysis

### LINKED ISSUE #10: `PathCondition::simplify()` is incorrect
The current implementation of `PathCondition::simplify()` is incorrect. It may not produce the simplest DNF (i.e., SOP) form for certain inputs, which may cause the path conditions analyzer not terminating.

### PR DESCRIPTION
**Pull request by henryhchchc**
Closes #10

### CODE REVIEW

**Comment by henryhchchc** [comment]
It works but it got stuck for some JDK classes. Some are due to timeout in the dependent library.

File: src/ir/control_flow/path_condition/mod.rs [hunk 1]
```diff
@@ -67,151 +102,184 @@ impl<P: Display> Display for Conjunction<P> {
...
+            // Return early to avoid causing errors in `quine_mccluskey`.
+            return;
+        }
+        let variable_ids = self.variable_ids();
+        let idx_count = variable_ids.len();
+        if variable_ids.len() > qmc::DEFAULT_VARIABLES.len() {
+            unimplemented!(
+                "`quine_mccluskey` supports only up to {} variables",
+                qmc::DEFAULT_VARIABLES.len()
+            );
```
Comment (Derppening) [inline src/ir/control_flow/path_condition/mod.rs:170]: I wonder if it would be better if we return `Result<(), SomeErrorType>` for `simplify` to explicitly signal a precondition that is unmet.

**Review by Derppening — COMMENTED** [review]
I am not too familiar with path simplification, so I cannot really comment on the implementation.

However, I do want to ask - What is the future plan for path simplification where there are more than 26 variables? It might be helpful to document this limitation somewhere (other than the API documentation) and state our plans regarding this.

**Comment by henryhchchc** [comment]
@Derppening 

> I am not too familiar with path simplification, so I cannot really comment on the implementation.

Well it is essentially given a constraint in [DNF](https://en.wikipedia.org/wiki/Disjunctive_normal_form) and we try to simplify it in a deterministic way.

> However, I do want to ask - What is the future plan for path simplification where there are more than 26 variables?

Hummm. I think we may need to fork `quine_mccluskey` and extend the number of variables it supports.

>  It might be helpful to document this limitation somewhere (other than the API documentation) and state our plans regarding this.

Yes we can document the limitation for now.

**Comment by henryhchchc** [comment]
I realized that we don’t need to adhere to the simplified form of path conditions. Instead, we can keep accumulating the minterms until they reach a fixed point. This guarantees that our path condition analyzer terminates. Alternatively, we can leave it to the user to simplify the constraint.

**Comment by henryhchchc** [comment]
The path condition analyzer should terminate now but the memory consumption is high. We should probably use things like BitSet to simplify it

**Comment by henryhchchc** [comment]
@Derppening I think we can try to merge it for now and optimize in a future PR.

**Review by Derppening — APPROVED** [review]
I think this looks good. Let's merge this first.
